sudo: required

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6

before_install:
  - openssl aes-256-cbc -K $encrypted_559dbc10541b_key -iv $encrypted_559dbc10541b_iv -in gcs-key.pem.enc -out gcs-key.pem -d

language: generic

script:
  - ./ci-test
