#!/bin/bash

set -eux

ACCESS_ID="etel-ci@api-project-992270938682.iam.gserviceaccount.com"

VERB=GET
CONTENT_MD5=
CONTENT_TYPE=
EXPIRES=$[ $(date +%s) + 60 ]

BUCKET=8b89942f-6dec-427f-944b-d66f1da83662
DEPS_FILE=deps-1.0.0.tgz

SIGNATURE=$(openssl sha -sha256 \
            -sign gcs-key.pem < \
            <(echo -ne \
              "${VERB}\n${CONTENT_MD5}\n${CONTENT_TYPE}\n${EXPIRES}\n/${BUCKET}/${DEPS_FILE}") | \
            base64 | \
            tr -d '\n' | \
            sed 's/+/%2B/g' | \
            sed 's,/,%2F,g' | \
            sed 's/=/%3D/g')

QUERY="GoogleAccessId=${ACCESS_ID}&Expires=${EXPIRES}&Signature=${SIGNATURE}"

DEPS_URL="https://storage.googleapis.com/${BUCKET}/${DEPS_FILE}?${QUERY}"

mkdir -p deps
curl -s "${DEPS_URL}" \
  | tar -C deps -zx

./deps/setup
make test
