#!/bin/bash

set -eux

where=$(dirname ${0})

MAJOR=1
MINOR=0
PATCH=0

ACCESS_ID="etel-ci@api-project-992270938682.iam.gserviceaccount.com"

VERB=GET
CONTENT_MD5=
CONTENT_TYPE=
EXPIRES=$[ $(date +%s) + 60 ]

BUCKET=8b89942f-6dec-427f-944b-d66f1da83662
DEPS_FILE=deps-1.0.0.tgz

SIGNATURE=$(openssl sha -sha256 \
            -sign ci/gcs-key.pem < \
            <(echo -ne \
              "${VERB}\n${CONTENT_MD5}\n${CONTENT_TYPE}\n${EXPIRES}\n/${BUCKET}/${DEPS_FILE}") | \
            base64 | \
            tr -d '\n' | \
            sed 's/+/%2B/g' | \
            sed 's,/,%2F,g' | \
            sed 's/=/%3D/g')

QUERY="GoogleAccessId=${ACCESS_ID}&Expires=${EXPIRES}&Signature=${SIGNATURE}"

DEPS_URL="https://storage.googleapis.com/${BUCKET}/${DEPS_FILE}?${QUERY}"

# Extract outside project directory.
# Works well for LCOV --no-external.
sudo mkdir -p /usr/local/8l/deps

curl -s "${DEPS_URL}" \
  | sudo tar -C /usr/local/8l/deps -zx

# Default behavior of tar for superuser is to preserve permissions!
sudo chmod 755 /usr/local/8l/deps

# This should setup ${HOME}/.make.defaults with paths to dependencies available from the downloaded file.
/usr/local/8l/deps/setup

# Add 'covreport' recipe to ${HOME}/.make.defaults
cat >> ${HOME}/.make.defaults <<EOF
covreport: coverage
	${where}/report-coverage
EOF

make covreport

# If master branch, update coverage report.
if [ "${TRAVIS_BRANCH}" != "master" ]
then
  exit 0
fi

# Setup access to github.
openssl aes-256-cbc -K ${encrypted_34d978248922_key} -iv ${encrypted_34d978248922_iv} -in ci/travis_rsa.enc -out ci/travis_rsa -d

mv ci/travis_rsa ${HOME}/.ssh/
chmod 400 ${HOME}/.ssh/travis_rsa

cat >> ${HOME}/.ssh/config <<EOF
Host github.com
  HostName github.com
  User travis@travis-ci.org
  IdentityFile ${HOME}/.ssh/travis_rsa
  PasswordAuthentication no
EOF

BRANCH=$(git branch | grep -v '(no branch)' | grep '^*' | awk '{ print $2; }')
COMMIT=$(git rev-parse HEAD)

git checkout master

cat build/.coverage/summary >> ci/coverage-report
tail -5 ci/coverage-report > tmp
mv tmp ci/coverage-report

git add ci/coverage-report
git commit -m '[skip ci] Update coverage.'

git remote add origin2 git@github.com:jaaju/8l.git
git push origin2 master

tag="${MAJOR}.${MINOR}.${PATCH}-b$(date +%s)"
git tag -a -m '[skip ci] Build tag.' "${tag}"
git push origin2 : "${tag}"

rm -f ${HOME}/.ssh/travis_rsa
